name: Deploy to Surge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and Deploy
      run: |
        # Configurar Surge.sh
        run: npx surge ./ --domain Elec2-Partial1.surge.sh --token ${{ 437f459005c9a07d8425c0f90e88f17f}}
        surge token <437f459005c9a07d8425c0f90e88f17f> # Reemplazar <SURGE_API_KEY> con la API Key de Surge.
